import { Course } from "./graphUtils";

export const SAMPLE_CURRICULUM: Omit<Course, "status">[] = [
  // Year 1, Term 1
  {
    code: "CCPROG1",
    title: "Logic Formulation & Introductory Programming",
    units: 3,
    year: 1,
    term: 1,
    prerequisites: [],
  },
  {
    code: "LBYCPA1",
    title: "Introductory Programming Laboratory",
    units: 1,
    year: 1,
    term: 1,
    prerequisites: [],
  },
  {
    code: "MTH101A",
    title: "Differential Calculus",
    units: 3,
    year: 1,
    term: 1,
    prerequisites: [],
  },
  {
    code: "DISMATH",
    title: "Discrete Structures I",
    units: 3,
    year: 1,
    term: 1,
    prerequisites: [],
  },

  // Year 1, Term 2
  {
    code: "CCPROG2",
    title: "Programming with Structured Data Types",
    units: 3,
    year: 1,
    term: 2,
    prerequisites: ["CCPROG1"],
  },
  {
    code: "LBYCPA2",
    title: "Structured Programming Laboratory",
    units: 1,
    year: 1,
    term: 2,
    prerequisites: ["LBYCPA1"],
  },
  {
    code: "MTH201A",
    title: "Integral Calculus",
    units: 3,
    year: 1,
    term: 2,
    prerequisites: ["MTH101A"],
  },
  {
    code: "CSARCH1",
    title: "Computer Architecture I",
    units: 3,
    year: 1,
    term: 2,
    prerequisites: ["DISMATH"],
  },
  {
    code: "LBYARCH",
    title: "Computer Architecture Laboratory",
    units: 1,
    year: 1,
    term: 2,
    prerequisites: ["DISMATH"],
  },

  // Year 2, Term 1
  {
    code: "CCPROG3",
    title: "Object-Oriented Programming",
    units: 3,
    year: 2,
    term: 1,
    prerequisites: ["CCPROG2"],
  },
  {
    code: "LBYCPA3",
    title: "OOP Laboratory",
    units: 1,
    year: 2,
    term: 1,
    prerequisites: ["LBYCPA2"],
  },
  {
    code: "STALGCM",
    title: "Algorithms and Complexity",
    units: 3,
    year: 2,
    term: 1,
    prerequisites: ["CCPROG2", "DISMATH"],
  },
  {
    code: "CSARCH2",
    title: "Computer Architecture II",
    units: 3,
    year: 2,
    term: 1,
    prerequisites: ["CSARCH1"],
  },
  {
    code: "LBYARC2",
    title: "Advanced Architecture Laboratory",
    units: 1,
    year: 2,
    term: 1,
    prerequisites: ["LBYARCH"],
  },

  // Year 2, Term 2
  {
    code: "STADVDB",
    title: "Database Management Systems",
    units: 3,
    year: 2,
    term: 2,
    prerequisites: ["CCPROG3"],
  },
  {
    code: "LBYDB01",
    title: "Database Systems Laboratory",
    units: 1,
    year: 2,
    term: 2,
    prerequisites: ["LBYCPA3"],
  },
  {
    code: "CSNETWK",
    title: "Data Communications and Networking",
    units: 3,
    year: 2,
    term: 2,
    prerequisites: ["CSARCH2"],
  },
  {
    code: "LBYNETW",
    title: "Computer Networking Laboratory",
    units: 1,
    year: 2,
    term: 2,
    prerequisites: ["LBYARC2"],
  },
  {
    code: "CSOPSYS",
    title: "Operating Systems Principles",
    units: 3,
    year: 2,
    term: 2,
    prerequisites: ["CSARCH2"],
  },

  // Year 3, Term 1
  {
    code: "STSWENG",
    title: "Software Engineering Principles",
    units: 3,
    year: 3,
    term: 1,
    prerequisites: ["STADVDB", "STALGCM"],
  },
  {
    code: "LBYSWEN",
    title: "Software Engineering Laboratory",
    units: 1,
    year: 3,
    term: 1,
    prerequisites: ["LBYDB01"],
  },
  {
    code: "CSSECDV",
    title: "Secure Web and Mobile Development",
    units: 3,
    year: 3,
    term: 1,
    prerequisites: ["STADVDB"],
  },
  {
    code: "CS ELEC 1",
    title: "CS Elective 1: Mobile App Engineering",
    units: 3,
    year: 3,
    term: 1,
    prerequisites: ["CCPROG3"],
  },

  // Year 3, Term 2
  {
    code: "THS-ST1",
    title: "Thesis Writing I (Research & Proposal)",
    units: 3,
    year: 3,
    term: 2,
    prerequisites: ["STSWENG"],
  },
  {
    code: "ST-DS01",
    title: "Machine Learning & Data Science",
    units: 3,
    year: 3,
    term: 2,
    prerequisites: ["STALGCM", "MTH201A"],
  },
  {
    code: "LBYML01",
    title: "Machine Learning Laboratory",
    units: 1,
    year: 3,
    term: 2,
    prerequisites: ["LBYSWEN"],
  },
  {
    code: "CS ELEC 2",
    title: "CS Elective 2: Cloud Computing & DevOps",
    units: 3,
    year: 3,
    term: 2,
    prerequisites: ["CSNETWK"],
  },

  // Year 4, Term 1
  {
    code: "THS-ST2",
    title: "Thesis Writing II (Implementation)",
    units: 3,
    year: 4,
    term: 1,
    prerequisites: ["THS-ST1"],
  },
  {
    code: "CSDISTB",
    title: "Distributed Systems & Parallel Computing",
    units: 3,
    year: 4,
    term: 1,
    prerequisites: ["CSNETWK", "CSOPSYS"],
  },
  {
    code: "CS ELEC 3",
    title: "CS Elective 3: Natural Language Processing",
    units: 3,
    year: 4,
    term: 1,
    prerequisites: ["ST-DS01"],
  },

  // Year 4, Term 2
  {
    code: "THS-DEF",
    title: "Thesis Defense & Capstone Final",
    units: 3,
    year: 4,
    term: 2,
    prerequisites: ["THS-ST2"],
  },
  {
    code: "FREE ELEC",
    title: "Free Elective: UI/UX & Human-Computer Interaction",
    units: 3,
    year: 4,
    term: 2,
    prerequisites: ["CSSECDV"],
  },
  {
    code: "PRC-ST2",
    title: "Industry Practicum / On-the-Job Training",
    units: 6,
    year: 4,
    term: 2,
    prerequisites: ["THS-ST2"],
  },
];
